search_term: Talent
no_of_search_pages: 2
no_of_target_connections: 15

filter_location:
  filter_bool: True
  filter_location: United States

filter_company:
  filter_bool: True
  filter_company: Progressive Insurance
